import '../models/nutrition_models.dart';

/// A line-for-line port of `src/nutrition/nutrition-math.ts`.
///
/// This file is not a convenience — it is a **contract**. The server
/// recomputes `grams` from `quantity × serving.grams` and rejects a log
/// whose supplied grams disagree by more than `max(0.1, 1%)`. If the two
/// sides round differently, logging fails with a validation error the user
/// cannot act on. So the arithmetic here mirrors the TypeScript exactly,
/// down to the epsilon nudge, and `test/nutrition_math_test.dart` pins the
/// results against vectors generated by running the server's own code.
class NutritionMath {
  const NutritionMath._();

  /// `Number.EPSILON`. JavaScript's `round()` adds this before scaling so a
  /// value sitting a hair below an exact half — the usual float artefact,
  /// e.g. `1.005` stored as `1.00499999999999989` — still rounds up. Dart
  /// has no built-in equivalent, so it is spelled out to keep the two
  /// implementations bit-for-bit comparable.
  static const double _epsilon = 2.220446049250313e-16;

  static double round(double value, [int places = 2]) {
    final double factor = _pow10(places);
    return ((value + _epsilon) * factor).round() / factor;
  }

  static double _pow10(int places) {
    double result = 1;
    for (int i = 0; i < places; i++) {
      result *= 10;
    }
    return result;
  }

  /// Scales a frozen per-100 g snapshot to the mass actually eaten.
  static Macros macrosForGrams(Macros per100g, double grams) {
    final double factor = grams / 100;
    return Macros(
      kcal: round(per100g.kcal * factor),
      proteinG: round(per100g.proteinG * factor),
      carbsG: round(per100g.carbsG * factor),
      fatG: round(per100g.fatG * factor),
    );
  }

  /// Sums macros **rounding at every step**, exactly as the server does.
  ///
  /// Summing first and rounding once gives a different answer, and the
  /// difference is visible: the daily total on the summary screen would
  /// disagree with the server's by a few tenths, which reads as a bug in
  /// whichever number the user happens to trust less.
  static Macros sumMacros(Iterable<Macros> values) {
    Macros total = Macros.zero;
    for (final Macros value in values) {
      total = Macros(
        kcal: round(total.kcal + value.kcal),
        proteinG: round(total.proteinG + value.proteinG),
        carbsG: round(total.carbsG + value.carbsG),
        fatG: round(total.fatG + value.fatG),
      );
    }
    return total;
  }

  /// The canonical portion calculation: `grams = quantity × serving.grams`.
  ///
  /// Every gram figure sent to the server must come from here. Computing
  /// it any other way is what makes a log fail validation.
  static double servingQuantityToGrams(double servingGrams, double quantity) {
    if (!servingGrams.isFinite || servingGrams <= 0) {
      throw ArgumentError.value(
        servingGrams,
        'servingGrams',
        'Must be positive',
      );
    }
    if (!quantity.isFinite || quantity <= 0) {
      throw ArgumentError.value(quantity, 'quantity', 'Must be positive');
    }
    return round(servingGrams * quantity);
  }

  /// The server's acceptance window, mirrored so the client can tell
  /// *before* sending whether a request would be rejected.
  static bool isMatchingGramAmount(double supplied, double expected) {
    final double tolerance = _maxOf(0.1, expected * 0.01);
    return (supplied - expected).abs() <= tolerance;
  }

  static double _maxOf(double a, double b) => a > b ? a : b;

  /// Normalises a serving label for comparison.
  ///
  /// Mirrors `labelKey()` in `nutrition.service.ts`. The server matches the
  /// `unitLabel` you send against the food's servings using this, so
  /// "1 Katori" and "1  katori" resolve to the same portion — and a label
  /// that does not normalise to one of them is rejected outright.
  static String labelKey(String value) =>
      value.toLowerCase().replaceAll(RegExp(r'\s+'), ' ').trim();

  /// Labels the server accepts as "the quantity IS the gram count".
  ///
  /// Mirrors the `['g', 'gram', 'grams']` branch in `expectedItemGrams`.
  static const Set<String> gramUnitLabels = <String>{'g', 'gram', 'grams'};

  static bool isGramUnitLabel(String label) =>
      gramUnitLabels.contains(labelKey(label));
}
